version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: btc-wallet
      POSTGRES_PASSWORD: btc-wallet

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: btc-wallet
      POSTGRES_USER: btc-wallet
      POSTGRES_PASSWORD: btc-wallet
